(cl:in-package anker_data_publish-msg)
(cl:export '(TIME_S-VAL
          TIME_S
          GX-VAL
          GX
          GY-VAL
          GY
          GZ-VAL
          GZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          ODO_RIGHT_POS-VAL
          ODO_RIGHT_POS
          ODO_LEFT_POS-VAL
          ODO_LEFT_POS
          ODO_RIGHT_VEL-VAL
          ODO_RIGHT_VEL
          ODO_LEFT_VEL-VAL
          ODO_LEFT_VEL
          OPT_POS_X-VAL
          OPT_POS_X
          OPT_POS_Y-VAL
          OPT_POS_Y
          OPT_QUALITY-VAL
          OPT_QUALITY
          WALL_DISTANCE_RIGHT-VAL
          WALL_DISTANCE_RIGHT
          WALL_DISTANCE_LEFT-VAL
          WALL_DISTANCE_LEFT
))